import type { CatalogEntry } from '../types.js';

/** FreeLLMAPI chat platforms — OpenAI-compat unless noted. */
export const FREELLMAPI_CATALOG: CatalogEntry[] = [
  {
    id: 'google',
    label: 'Google (Gemini)',
    tier: 3,
    protocol: 'gemini',
    authStyle: 'query-key',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    defaultModel: 'gemini-2.5-flash',
    capabilities: ['tools', 'vision', 'streaming'],
    source: 'freellmapi',
    catalogReady: false,
    timeoutMs: 60_000,
  },
  {
    id: 'groq',
    label: 'Groq',
    tier: 3,
    protocol: 'openai',
    authStyle: 'bearer',
    baseUrl: 'https://api.groq.com/openai/v1',
    defaultModel: 'llama-3.3-70b-versatile',
    capabilities: ['tools', 'vision', 'streaming'],
    source: 'both',
    catalogReady: true,
  },
  {
    id: 'cerebras',
    label: 'Cerebras',
    tier: 3,
    protocol: 'openai',
    authStyle: 'bearer',
    baseUrl: 'https://api.cerebras.ai/v1',
    defaultModel: 'gpt-oss-120b',
    capabilities: ['tools', 'streaming'],
    source: 'both',
    catalogReady: true,
  },
  {
    id: 'nvidia',
    label: 'NVIDIA NIM',
    tier: 3,
    protocol: 'openai',
    authStyle: 'bearer',
    baseUrl: 'https://integrate.api.nvidia.com/v1',
    defaultModel: 'minimaxai/minimax-m2.7',
    capabilities: ['tools', 'streaming'],
    source: 'both',
    catalogReady: true,
    timeoutMs: 90_000,
  },
  {
    id: 'mistral',
    label: 'Mistral',
    tier: 3,
    protocol: 'openai',
    authStyle: 'bearer',
    baseUrl: 'https://api.mistral.ai/v1',
    defaultModel: 'mistral-large-latest',
    capabilities: ['tools', 'vision', 'streaming'],
    source: 'both',
    catalogReady: true,
  },
  {
    id: 'openrouter',
    label: 'OpenRouter',
    tier: 3,
    protocol: 'openai',
    authStyle: 'bearer',
    baseUrl: 'https://openrouter.ai/api/v1',
    defaultModel: 'openrouter/auto',
    capabilities: ['tools', 'vision', 'streaming'],
    source: 'both',
    catalogReady: true,
    extraHeaders: {
      'HTTP-Referer': 'https://helmora.local',
      'X-Title': 'Helmora AI',
    },
  },
  {
    id: 'github',
    label: 'GitHub Models',
    tier: 3,
    protocol: 'openai',
    authStyle: 'bearer',
    baseUrl: 'https://models.github.ai/inference',
    defaultModel: 'openai/gpt-4.1',
    capabilities: ['tools', 'streaming'],
    source: 'freellmapi',
    catalogReady: true,
  },
  {
    id: 'cohere',
    label: 'Cohere',
    tier: 3,
    protocol: 'openai',
    authStyle: 'bearer',
    baseUrl: 'https://api.cohere.ai/compatibility/v1',
    defaultModel: 'command-r-plus-08-2024',
    capabilities: ['tools', 'streaming'],
    source: 'both',
    catalogReady: true,
  },
  {
    id: 'cloudflare',
    label: 'Cloudflare Workers AI',
    tier: 3,
    protocol: 'openai',
    authStyle: 'account_token',
    baseUrl: 'https://api.cloudflare.com/client/v4/accounts/{accountId}/ai/v1',
    defaultModel: '@cf/meta/llama-3.1-70b-instruct',
    capabilities: ['tools', 'streaming'],
    source: 'both',
    catalogReady: true,
  },
  {
    id: 'zhipu',
    label: 'Zhipu / BigModel (paas)',
    tier: 3,
    protocol: 'openai',
    authStyle: 'bearer',
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    defaultModel: 'glm-4.5-flash',
    capabilities: ['tools', 'streaming'],
    source: 'freellmapi',
    catalogReady: true,
  },
  {
    id: 'ollama',
    label: 'Ollama Cloud',
    tier: 3,
    protocol: 'openai',
    authStyle: 'bearer',
    baseUrl: 'https://ollama.com/v1',
    defaultModel: 'gpt-oss:120b',
    capabilities: ['tools', 'streaming'],
    source: 'both',
    catalogReady: true,
    timeoutMs: 120_000,
  },
  {
    id: 'kilo',
    label: 'Kilo Gateway',
    tier: 3,
    protocol: 'keyless',
    authStyle: 'none',
    baseUrl: 'https://api.kilo.ai/api/gateway/v1',
    defaultModel: 'nvidia/nemotron-3-super-120b-a12b:free',
    capabilities: ['tools', 'streaming'],
    source: 'freellmapi',
    catalogReady: true,
    keyless: true,
  },
  {
    id: 'pollinations',
    label: 'Pollinations',
    tier: 3,
    protocol: 'keyless',
    authStyle: 'none',
    baseUrl: 'https://text.pollinations.ai/openai/v1',
    defaultModel: 'openai-fast',
    capabilities: ['tools', 'streaming'],
    source: 'freellmapi',
    catalogReady: true,
    keyless: true,
  },
  {
    id: 'llm7',
    label: 'LLM7',
    tier: 3,
    protocol: 'openai',
    authStyle: 'bearer',
    baseUrl: 'https://api.llm7.io/v1',
    defaultModel: 'codestral-latest',
    capabilities: ['tools', 'streaming'],
    source: 'freellmapi',
    catalogReady: true,
  },
  {
    id: 'huggingface',
    label: 'HuggingFace Router',
    tier: 3,
    protocol: 'openai',
    authStyle: 'bearer',
    baseUrl: 'https://router.huggingface.co/v1',
    defaultModel: 'accounts/fireworks/models/llama-v3p3-70b-instruct',
    capabilities: ['tools', 'streaming'],
    source: 'both',
    catalogReady: true,
  },
  {
    id: 'opencode',
    label: 'OpenCode Zen',
    tier: 3,
    protocol: 'openai',
    authStyle: 'bearer',
    baseUrl: 'https://opencode.ai/zen/v1',
    defaultModel: 'big-pickle',
    capabilities: ['tools', 'streaming'],
    source: 'both',
    catalogReady: true,
  },
  {
    id: 'ovh',
    label: 'OVH AI Endpoints',
    tier: 3,
    protocol: 'keyless',
    authStyle: 'none',
    baseUrl: 'https://oai.endpoints.kepler.ai.cloud.ovh.net/v1',
    defaultModel: 'gpt-oss-120b',
    capabilities: ['tools', 'streaming'],
    source: 'freellmapi',
    catalogReady: true,
    keyless: true,
  },
  {
    id: 'agnes',
    label: 'Agnes AI',
    tier: 3,
    protocol: 'openai',
    authStyle: 'bearer',
    baseUrl: 'https://apihub.agnes-ai.com/v1',
    defaultModel: null,
    capabilities: ['tools', 'streaming'],
    source: 'freellmapi',
    catalogReady: true,
  },
  {
    id: 'reka',
    label: 'Reka',
    tier: 3,
    protocol: 'openai',
    authStyle: 'bearer',
    baseUrl: 'https://api.reka.ai/v1',
    defaultModel: 'reka-flash-3',
    capabilities: ['tools', 'vision', 'streaming'],
    source: 'freellmapi',
    catalogReady: true,
  },
  {
    id: 'siliconflow',
    label: 'SiliconFlow',
    tier: 3,
    protocol: 'openai',
    authStyle: 'bearer',
    baseUrl: 'https://api.siliconflow.com/v1',
    defaultModel: 'deepseek-ai/DeepSeek-V4-Pro',
    capabilities: ['tools', 'streaming'],
    source: 'both',
    catalogReady: true,
  },
  {
    id: 'aimlapi',
    label: 'AI/ML API',
    /** Default T3 for free-pool / trial testing; change tier in /providers when using paid. */
    tier: 3,
    protocol: 'openai',
    authStyle: 'bearer',
    baseUrl: 'https://api.aimlapi.com/v1',
    defaultModel: 'gpt-4o-mini',
    capabilities: ['tools', 'vision', 'streaming'],
    source: 'freellmapi',
    catalogReady: true,
  },
  {
    id: 'modelscope',
    label: 'ModelScope',
    tier: 3,
    protocol: 'openai',
    authStyle: 'bearer',
    baseUrl: 'https://api-inference.modelscope.cn/v1',
    defaultModel: 'Qwen/Qwen3-30B-A3B-Instruct-2507',
    capabilities: ['tools', 'streaming'],
    source: 'freellmapi',
    catalogReady: true,
  },
  {
    id: 'kiraai',
    label: 'Kira AI',
    tier: 3,
    protocol: 'openai',
    authStyle: 'bearer',
    baseUrl: 'https://kiraai.vn/api/v1',
    defaultModel: 'kira-3.5-pro',
    capabilities: ['tools', 'streaming'],
    source: 'freellmapi',
    catalogReady: true,
  },
  {
    id: 'routeway',
    label: 'Routeway',
    tier: 3,
    protocol: 'openai',
    authStyle: 'bearer',
    baseUrl: 'https://api.routeway.ai/v1',
    defaultModel: null,
    capabilities: ['tools', 'streaming'],
    source: 'freellmapi',
    catalogReady: true,
    extraHeaders: {
      'User-Agent': 'Mozilla/5.0 HelmoraAI/1.0',
    },
  },
  {
    id: 'bazaarlink',
    label: 'BazaarLink',
    tier: 3,
    protocol: 'openai',
    authStyle: 'bearer',
    baseUrl: 'https://bazaarlink.ai/api/v1',
    defaultModel: 'auto:free',
    capabilities: ['tools', 'streaming'],
    source: 'freellmapi',
    catalogReady: true,
  },
  {
    id: 'ainative',
    label: 'AINative Studio',
    tier: 3,
    protocol: 'openai',
    authStyle: 'bearer',
    baseUrl: 'https://api.ainative.studio/api/v1',
    defaultModel: null,
    capabilities: ['tools', 'streaming'],
    source: 'freellmapi',
    catalogReady: true,
  },
  {
    id: 'aion',
    label: 'Aion Labs',
    tier: 3,
    protocol: 'openai',
    authStyle: 'bearer',
    baseUrl: 'https://api.aionlabs.ai/v1',
    defaultModel: null,
    capabilities: ['tools', 'streaming'],
    source: 'freellmapi',
    catalogReady: true,
  },
  {
    id: 'requesty',
    label: 'Requesty',
    tier: 3,
    protocol: 'openai',
    authStyle: 'bearer',
    baseUrl: 'https://router.requesty.ai/v1',
    defaultModel: null,
    capabilities: ['tools', 'streaming'],
    source: 'freellmapi',
    catalogReady: true,
  },
  {
    id: 'nara',
    label: 'NaraRouter',
    tier: 3,
    protocol: 'openai',
    authStyle: 'bearer',
    baseUrl: 'https://router.bynara.id/v1',
    defaultModel: 'mistral-large',
    capabilities: ['tools', 'streaming'],
    source: 'freellmapi',
    catalogReady: true,
  },
  {
    id: 'aihorde',
    label: 'AI Horde',
    tier: 3,
    protocol: 'keyless',
    authStyle: 'none',
    baseUrl: 'https://oai.aihorde.net/v1',
    defaultModel: 'auto',
    capabilities: ['streaming'],
    source: 'freellmapi',
    catalogReady: true,
    keyless: true,
    timeoutMs: 120_000,
  },
];
